In [1]:
import numpy as np

# Array Creation Routines

In [72]:
# similar to range function
np.arange(start=10, stop=20, step=1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
# like arange but specify number of steps instead of size of steps
np.linspace(start=10, stop=20, num=21)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [67]:
# array of zeros
np.zeros(shape=(3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
# array of ones
np.ones(shape=(2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
# array filled with any value
np.full(shape=(2, 5), fill_value='anything')

array([[41, 41, 41, 41, 41],
       [41, 41, 41, 41, 41]])

In [78]:
# apply function to array coordinates
np.fromfunction(lambda x, y: x*y, shape=(10, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 0.,  6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 0.,  7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 0.,  9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [80]:
# get identity matrix (as array)
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
# split string into array
np.fromstring('1 2 4', dtype=int, sep=' ')

array([1, 2, 4])

In [31]:
np.random.binomial(n=100, p=.5, size=5)

array([55, 57, 55, 49, 39])