In [1]:
import numpy as np

# Arrays

## Arrays vs Lists

Biggest differences:
- Arrays are much more computationally efficient (faster operations, less memory)
- Array elements are all of same type
- Operators behave differently
- Arrays cannot be resized

In [2]:
# this will be an array of all strings
np.array([1.4, '5', 8])

array(['1.4', '5', '8'], dtype='<U32')

In [3]:
# this will be an array of all floats
np.array([2, 4, 9.0])

array([2., 4., 9.])

In [4]:
# operators behave differently
arr1 = np.array([1, 2, 3, 4, 5, 6])

arr1 * 8

array([ 8, 16, 24, 32, 40, 48])

In [5]:
arr2 = np.array([10, 20, 30, 40, 50, 60])

arr1 + arr2

array([11, 22, 33, 44, 55, 66])

## Attributes

In [6]:
arr = np.array([[1, 2, 4], [8, 10, 4]])
# array shape
arr.shape

(2, 3)

In [7]:
# total size
arr.size

6

In [8]:
# number of dimensions
arr.ndim

2

In [9]:
# data type
arr.dtype

dtype('int32')